### ISSUE TITLE
[TODO] Module Base

### ISSUE THREAD

**Issue by NewtTheWolf** [TieCMS/TieCMS#12]
- [ ] Refactor with Itoh
- [ ] Create Config Reader
- [ ] Create Permission Checker
- [ ] Database Connection
